name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust to the branch you want to deploy from (e.g., `main` or `master`)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'  # Set your Node.js version here

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Run your build script (make sure it's working locally first)

      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version  # Check Firebase CLI version

      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMARA__VOICE }}" > $GITHUB_ENV
          
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project amara--voice --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMARA__VOICE }}
