name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Change this to your default branch, if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Or whatever version you are using

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Set up Firebase CLI
        uses: wzieba/Firebase-Action@v2
        with:
          firebase_token: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMARA__VOICE }}

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMARA__VOICE }}
